### ISSUE TITLE
heroku sandbox deploy doesn't show child pages

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/Sandbox#7] opened 2017-04-06 14:08 UTC
guessing its a config / jekyll serve issue with heroku cloud, so wondering if the jekyll structure/config/serve question should be handled first.

**Comment by kateefly** [comment] 2017-04-06 14:11
I can confirm at least that you do see child pages on a local jekyll instance using a clone of this repository (I saw them when I was taking a look at how the theme worked yesterday).

**Comment by cmh2166** [comment] 2017-04-06 14:11
yeah. me too.

**Comment by kateefly** [comment] 2017-04-17 16:32
I think this is because it wants the href to be "pagename.html" and not simply "pagename" as it is currently in the includes navigation file.

**Comment by kateefly** [comment] 2017-06-01 20:58
Fixed with commit 28982c9eca4ccc89067ed30bf8430f03185caad1

**Closed by kateefly** 2017-06-01 20:58 UTC
Labels: bug
